### ISSUE TITLE
check for StateIdle?

### ISSUE THREAD

**Issue by jmhodges** [tylerb/graceful#72]
Looks like graceful doesn't track connections going to StateIdle and waits for them to completely timeout. This means servers with very long idle timeouts always have to wait for their connections to timeout or set a more aggressive timeout for the graceful shutdown. The more aggressive timeout is not quite what we want since that could shut down the server while there are requests still in flight. 

It would be nice for graceful to track idle connection states, close them when shutdown is initiated, and not count them against the server being able to close.

**Comment by F21** [comment]
I think this would be pretty nice. Are you able to work on a PR?

**Comment by jmhodges** [comment]
Nah, but someone could take a look at github.com/facebookgo/httpdown and work it out from there.

**Comment by tylerb** [comment]
This should be a very simple fix. It looks like we are explicitly removing the idle connections from the pool of tracked connections.

**Comment by tylerb** [comment]
Nope, it was removed completely for some reason. Whoops.

**Comment by tylerb** [comment]
Fixed in 7b1ea4990f7486251b24ebabc0487546ad924700

@F21 I think this fix addresses the same issue that you addressed in #70. Can you please test this again to see if my fix addresses your issue. If possible, I'd like to remove your fix in favor of this one if it solves that same issue. Thanks!

**Comment by F21** [comment]
@tylerb Awesome! Thanks for working on this. Your commit deals with idle connections preventing the server from shutting down, whereas #70 drops idle connections when the server is running normally (not shutting down) so that they do not consume resources and file descriptors indefinitely. See https://github.com/golang/go/commit/d6bce32a3607222075734bf4363ca3fea02ea1e5 and https://groups.google.com/forum/#!topic/golang-dev/zh6frmUA8no

**Comment by tylerb** [comment]
Perfect. Thanks for the distinction. Looks like we are good to go!

Thanks for reporting this, Jeff!
