### ISSUE TITLE
Feature Request: A More Flexible Logging

### ISSUE THREAD

**Issue by bangzek** [tylerb/graceful#74]
It seem your package use/depend on the built-in log package.

While its reasonable, I propose a more flexible logging along the line of https://0value.com/about-Go-logging so the user of your package could use and choose another logging solution.

EDIT: The change is minimal, while it broke the ABI
[graceful-patch.txt](https://github.com/tylerb/graceful/files/321957/graceful-patch.txt)

TIA

**Comment by F21** [comment]
ping @tylerb

**Comment by tylerb** [comment]
I'm a bit loathe to make this change, as it is a breaking change. It could be done in a non-breaking way by just adding the func alongside the current one and calling it if it exists instead of logging to the default logger. That, though, also seems awful.

I think I'll add the func alongside the builtin for now, but I think it's time for a rewrite of graceful. This was created years ago and it deserves to be rewritten with all the new knowledge and experience everyone has gained since then.

**Comment by tylerb** [comment]
Fixed in 7e8415b880c4f556200f24f2c1c7b1f07ac0fa1d
